### ISSUE TITLE
Add absolute time assignments for individual element and absolute time.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#10]
We need to add a pop up table (similar to the "View List of Assignments"), where there is a table where each row is each graph node and each column is an absolute time. The table will have drop down boxes for evaluation labels, so the user can assign an evaluation to an element at a time.
Use only short-forms (FS, T) for each element and add a Legend at the bottom to keep the table cleaner.
Grey out (and make deactivated) the boxes that are already defined by a function. For example, a Constant (FS, T) function would have the entire row as (FS, T) but all inactive.

Note: Required to completely do AR2 and AR3 from RE'16 paper with absolute time.

**Comment by g2hchang** [comment]
Refer to #57
