### ISSUE TITLE
Syntax Checking for Evolving Decomposition

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#12]
There are many invalid combinations of decomposition links. For example:
![screen shot 2017-08-14 at 4 48 05 pm](https://user-images.githubusercontent.com/6596937/29291092-6dfcefd0-8110-11e7-96f1-000976559b08.png)

Add syntax checking when you click analysis to show users errors.

**Comment by Akira83** [comment]
Could you clarify this a little bit more? In this example, why is this combination invalid? What I could understand is that in the beginning the Goal_0 can be decomposed in Goal_1 and Goal_2. Then somewhere in next steps it will be only decomposed in Goal_1 without any relationship between Goal_2.

**Comment by amgrubb** [comment]
Will do, this is of lower importance so it might take me a bit of time. I will assign myself so I will get back to it.

**Comment by g2hchang** [comment]
Links with #87

**Comment by g2hchang** [comment]
Pull request #115 merged.
