### ISSUE TITLE
Add node names (& actor) to over-constrained error message.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#125]
The error message currently looks like this:
![screen shot 2018-04-04 at 10 55 49 am](https://user-images.githubusercontent.com/6596937/38315657-e9985916-37f6-11e8-8775-84c20003fbc1.png)

Can we parse the error message to get N0039 etc. and create a mapping for the user to node name, maybe including actor.

N0039 = Find Car

**Comment by amgrubb** [comment]
![screen shot 2018-05-17 at 5 37 12 pm](https://user-images.githubusercontent.com/6596937/40205157-04588e28-59f9-11e8-8043-e04a9088f063.png)

Here is a sample model the generates an error.

**Comment by nasirhemed** [comment]
Can you elaborate more on this? Where is this error generated and and how do you want us to map the user to node name ?

**Comment by amgrubb** [comment]
This might have to wait until next week, because I don't know how much I can explain over text.
The error is generated by the backend and passed to an alert.

In backendComm.js (line ~55):
```	//Executing action to send backend
	$.ajax({
		url: pathToCGI,
		type: "get",
		success: function(response){
			analysisResults = JSON.parse(response['data']);
			var errorMsg = analysisResults.errorMessage;
			if(errorMsg){
				alert(errorMsg);
			}```

I want you to add some parsing to the message before the alert. The ID N0039 is the same as created in the input file but there is an N attached by the backend.
Start by finding everything that has an "N" in it.

**Comment by nasirhemed** [comment]
@amgrubb Look at the backend...

**Comment by nasirhemed** [comment]
Issue fixed before refactoring
