### ISSUE TITLE
Soft-goal text not vertically centred. 

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#126]
I always add blank lines at the top of soft-goals so the text is centred.

**Comment by amgrubb** [comment]
Did you make the shape above?

Some people use a cloud shape, but that is not very regular.

By regular, do you mean symmetric or pre-defined in rappid? Would this work?
![screen shot 2018-05-23 at 5 39 19 pm](https://user-images.githubusercontent.com/6596937/40452586-5998c1d0-5eb0-11e8-8327-9ce40edc106f.png)

**Comment by xorye** [comment]
We have found a way to properly resize softgoals using SVG, with the new version of rappid and jointjs. I think we should resolve this issue after we upgrade rappid.

**Comment by Null7** [comment]
This is solved.

**Comment by nasirhemed** [comment]
No it isn't ... The soft goal still goes down. I think it will be resolved when we update rappid
