### ISSUE TITLE
Evolving Relationship Panel

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#13]
When you click on a previously created evolving relationship, the title and button (in the relationship panel) have to wrong wording.
![screen shot 2017-08-14 at 5 06 52 pm](https://user-images.githubusercontent.com/6596937/29291879-0237ca56-8113-11e7-9fc1-04cbe4c2e3a8.png)
Should be Evolving Relationship on the top and Constant Relationship on the button.

**Comment by Akira83** [comment]
Correction done in marcel-dev branch.
