### ISSUE TITLE
Syntax Checking Error Message

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#142]
Clean up the error message for the decomposition syntax checking.
Correct grammar and make it more readable.
Model on left, generate error by clicking analysis.

![screen shot 2018-05-14 at 3 09 52 pm](https://user-images.githubusercontent.com/6596937/40017947-e32fb090-5788-11e8-98a3-371c4e40b53a.png)

**Comment by amgrubb** [comment]
@nasirhemed Oh, why did you close this?

**Comment by nasirhemed** [comment]
Oh sorry I didn't know.
