### ISSUE TITLE
Tool is not responsive sometimes when loaded for the first time

### ISSUE THREAD

**Issue by nasirhemed** [amgrubb/BloomingLeaf#143]
Tool does not seem to work sometimes when it is loaded for the first time. The buttons and the nodes do not do anything when they are clicked.

![gif](https://user-images.githubusercontent.com/33851317/40066459-2325cf50-5832-11e8-91f6-e5b5dcedf070.gif)

**Comment by xorye** [comment]
It is difficult to reproduce this error, making it difficult to work on a fix. I will keep my eyes open for the next time this bug happens.

**Comment by nasirhemed** [comment]
Issue fixed
