### ISSUE TITLE
Test Project Demo for RE.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#146]
Walk through the procedure in the RE Demo Appendix, and determine what needs to be clarified.

What can be added.

**Comment by xorye** [comment]
Unclear things:

Figure 5, the node named "Have Design" has an evolving function "DS" and an initial
satisfaction value of Satisfied (FS, T). Currently, BloomingLeaf makes this behaviour
impossible. If the evolving function is Denied Satisfied, then the initial satisfaction
value should be Denied (T, FD) instead.
Both the master version and dev version of BloomingLeaf prevents the user from creating
a node with a Denied Satisfied function, with Satisfied as its initial satisfaction value.
![image](https://user-images.githubusercontent.com/20326645/40248056-a0b8a494-5a9c-11e8-985d-1bb452398092.png)



From the first column of page 4, it says "we see that Temporary Construction was selected by the simulation". I am confused as to where we see that the Temporary Construction was selected by the simulation.
![image](https://user-images.githubusercontent.com/20326645/40248191-1e344e0a-5a9d-11e8-853a-b25e4b081cdc.png)



In the second column of page 4, it states a ++ link has been added from Have Bike Lanes to
Temporary Construction, but figure 7 shows an AND link.
![image](https://user-images.githubusercontent.com/20326645/40248087-c0ba9b94-5a9c-11e8-914e-0e2b479b816f.png)



Unable to simulate paths with the current model. The following browser alert appears
after "Simulate Single Path" is selected. Tested on both the master branch version and dev branch version.
![image](https://user-images.githubusercontent.com/20326645/40248605-7b5fa0c4-5a9e-11e8-9d24-2a9007397752.png)


This was the model used:
(It is the same as the model in the RE appendix, with the exception of the initial satisfaction value for Have Design)
![image](https://user-images.githubusercontent.com/20326645/40248548-439f5ac6-5a9e-11e8-9963-df4ce2a21edc.png)

These were the analysis settings:
![image](https://user-images.githubusercontent.com/20326645/40248575-608d0fca-5a9e-11e8-9219-7c7c9189dd41.png)

These were the Absolute and Relative Assignments:
![image](https://user-images.githubusercontent.com/20326645/40248716-cf1a3db4-5a9e-11e8-8766-57e85adb2441.png)

**Comment by amgrubb** [comment]
Excellent Work @xorye 
I'm not sure about the runtime error that you got, maybe that is a different bug.
