### ISSUE TITLE
Representing non-binary evaluation labels in the backend.

### ISSUE THREAD

**Issue by xorye** [amgrubb/BloomingLeaf#155]
Currently, evaluation labels for intentions can be non-binary strings. For example, the string: "(no value)" is a valid evaluation label.

This is an issue in the backend because the backend assumes that all evaluation labels are 4 digit binary strings. Therefore, evaluation labels are being stored as boolean arrays of length 4. In order to have evaluation labels like "(no value)", there must be a different way to store evaluation labels in the backend. Quite possibly, variables and functions associated with `initialValues`, `initialValueTimePoints` and `initialAssignedEpochs` (found on lines 43 to 47 of `ModelSpec.java`) may need to be edited.

For the meantime, any evaluation label that is not a 4 digit binary string will be treated as the "0000" evaluation label. This behaviour is achieved by the `getEvaluationArray()` function in `ModelSpecBuilder.java`.

**Comment by oibrahim22** [comment]
We have not yet finalized a new method to represent evaluation labels in the backend.

**Comment by ibrodycalixto** [comment]
SPRINT WEEK OCT 1 @ibrodycalixto @YanningTan 

- [x] Completed notes/diagram on Tropos

- [x] Proposal for non-boolean value representation of nonexistent/undetermined

**Comment by ibrodycalixto** [comment]
SPRINT WEEK OCT 8 @ibrodycalixto @YanningTan 

- [ ] Yanning - Front End Class Diagram

- [x] Meet with Alicia about math, behaviors of undetermined/non-existent intentions

- [ ] Start implementing Front End/ Backend!

**Comment by ibrodycalixto** [comment]
SPRINT WEEK OCT 15 @ibrodycalixto @YanningTan 

- [x] Keep working on Front End Class Diagram

- [x] Read thesis, start list of constraints

- [ ] Start Front End Implementation

**Comment by ibrodycalixto** [comment]
SPRINT WEEK OCT 27 @ibrodycalixto @YanningTan 

- [ ] UND frontend implementation

- [x] Spec NE frontend implementation

- [x] Finish UND constraint list

**Comment by ibrodycalixto** [comment]
SPRINT WEEK NOV 15 @ibrodycalixto @YanningTan 

- [ ] Backend implementation of undetermined values

- [ ] Frontend implementation of und values

- [ ] Take care of ourselves <3
