### ISSUE TITLE
Deleting intentions causing indexing problems in backend.

### ISSUE THREAD

**Issue by xorye** [amgrubb/BloomingLeaf#156]
**Note:**
In order to see an example of this issue in the code, go to `ModelSpecBuilder.java` and Ctrl-F for "#156"

**About:** 
In the backend, `ModelSpecBuilder.java` and `ModelSpec.java` contains an array called `initialValues` where its indices correspond to intentions ids.

In order for indices to directly correspond to intention ids, there is one assumption that must be maintained. It is the following:

If `initialValues` had a length of `n` where `n` is the total current number of intentions, the backend assumes that there exists intentions with intention Ids `0`, `1`, `2`, ... , `n - 1`. 

**The issue:** 
However, let us consider the scenario where the user creates two intentions, the first intention having an Id of 0 and the second intention having an Id of 1. The user then proceeds to delete the first intention. This scenario violates the backend's assumption because `initialValues` would be of length `1` (because the total current number of intentions is 1), but an intention with Id 0 does not exist.

**What needs to be done:**
The way the `ModelSpecBuilder.java` and `ModelSpec.java` stores intention information in the `initialValues` array must change, in order to take into account the case where users delete intentions. There may be other arrays in the backend code that rely on the assumption mentioned earlier. Those arrays must also be changed as well.

**Comment by amgrubb** [comment]
Also linked with #166 #176

**Comment by oibrahim22** [comment]
This issue was fixed by not deleting the intention from the JSON file that gets sent to the backend but deleting its links, marking the function type "DT", and deleting function segments. This way the intentions indexing does not change.
