### ISSUE TITLE
Add a git commit pre-hook to enforce style guide.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#157]
Add a git commit pre-hook to enforce style guide.

I recommend using eslint, starting with the AirBnB style guide

Ideally set up as a git commit pre-hook to ensure that linting errors never end up in the repo itself
Atom has good support for eslint. Your text editor can find linting issues for you

https://medium.com/@shettyrahul8june/how-to-run-eslint-using-pre-commit-hook-25984fbce17e

**Comment by oibrahim22** [comment]
This issue was not discussed

**Comment by amgrubb** [comment]
Formatting can be done in VS Code now.
