### ISSUE TITLE
Exclude NB elements from absolute values table but NOT NB Links

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#17]
In the absolute values table (see below), NB elements should not appear in the top table.
Keep NBT and NBD links in the bottom table.

![screen shot 2017-08-16 at 12 16 53 pm](https://user-images.githubusercontent.com/6596937/29374114-5274b562-827e-11e7-9ddb-10933a8ab18f.png)

**Comment by Akira83** [comment]
Fixed.

**Comment by amgrubb** [comment]
Thanks!
