### ISSUE TITLE
Error Passing to User: Over-constrained model

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#19]
When the CSP solver discovers that the model is over-constrained it outputs:

`Constraint: And733 : And(Or2089 : Or( XeqC4971 : XeqC(N0046_0_PS=1, 0 ), XeqC4972 : XeqC(N0038_0_PS=0, 1 )),Or2090 : Or( XeqC4973 : XeqC(N0046_0_PD=0, 0 ), XeqC4974 : XeqC(N0038_0_PD::{0..1}, 1 )),,
have conflicting constraints, not solvable
Found Solution = False`

This should be passed to the front-end, parsed, and communicated to the user.

**Comment by g2hchang** [comment]
Incorporated into #95.
