### ISSUE TITLE
MMINT

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#222]

**Comment by lilakk** [comment]
- [x] Email Alessio

- [x] Continue working on setting up Travis with the forked MMINT repo

**Comment by lilakk** [comment]
- [x] Follow Alessio's email and try to set up Travis with MMINT. Email him again with further questions.

**Comment by sscrane** [comment]
- [x] Finish watching videos about MMINT
- [ ] Work on making the metamodel in MMINT
- [x] Try to break the MMINT code, upload to git, and see if Travis catches it

**Comment by lilakk** [comment]
- [ ] Look at how to add unit tests to Travis.

- [ ] Work on building metamodels in Eclipse if we hear back from Mouna.

**Comment by amgrubb** [comment]
Great job on this project!
