### ISSUE TITLE
EVO Study

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#223]

**Comment by kmbspencer** [comment]
Sprint Week October 1st - October 8th @mvarnum @kmbspencer 

- [ ] add screenshots to all models

- [ ] expand questions for all models

- [ ] start background paragraphs for models

- [ ] continue exploring qualtrics

- [ ] start planning training video

- [ ] make sprints!

**Comment by amgrubb** [comment]
This issue is out of date.
