### ISSUE TITLE
Undo / Redo breaks while using "Clear Model"

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#244]
When the model is cleared and then user attempts to walk through undo/redo, this can throw a series of errors due to elements not existing, or incorrect JSON formatting

To replicate: 
1. Load or create a model (In Model view) that includes multiple actors
2. Select "Clear - Full Model"
3. Click Undo (to restore the model)
4. Click Redo

BEFORE: 
<img width="1035" alt="Screen Shot 2020-12-05 at 1 57 07 PM" src="https://user-images.githubusercontent.com/37080292/101261000-d4d29e80-3701-11eb-8330-117cbbec6a76.png">
AFTER:
<img width="1440" alt="Screen Shot 2020-12-05 at 1 57 20 PM" src="https://user-images.githubusercontent.com/37080292/101261003-da2fe900-3701-11eb-91ee-eada37a6cc91.png">

One actors fails to reappear and an error appears. May be in part due to model management issues. Probably based in a data struct overlap that isn't handled well.

Other similar errors can be found by clearing individual elements and then walking through undo/redo enough times in any format. 

Additional Note/Bug: When selecting "Clear - Evaluation Labels", undo restores the labels one by one rather than as a whole. Should probably update this functionality to batch restore elements when Undo is selected. 

Message @esterzhao if more info is needed!

**Comment by amgrubb** [comment]
@Domily11 Please test this and see if it is still an issues.

**Comment by Domily11** [comment]
> @Domily11 Please test this and see if it is still an issues.

Yep, still an issue. I'll work on it
