### ISSUE TITLE
Save functionality for multiple analysis results

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#249]
* Create functionality to save analysis results details into the json file sent to backend (SORTED BY CONFIG INFO)
* Use gson to transform analysis results details into backend obj params 
* Update backend to send packaged model-analysis details back to the frontend in order to load full model-analyses

**Comment by amgrubb** [comment]
Completed as part of Save/Load PR in Backbone Refactoring.
