### ISSUE TITLE
Create analysis configurations/results sidebar

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#250]
* Update the front-end analysis view to include a sidebar where analysis configurations and results can be viewed and saved
* Make a decision on how to save analysis configurations -> autosave when switching between them, or required save button? How do you save the info on each configuration? Local hosted continuously updated list? **Alicia's note: analysis configurations are only saved once analysis is actually run**
* Generally update the UI to account for model management changes (ex. Scrape out history log, see if anything is usable)

**Comment by esterzhao** [comment]
SPRINT WEEK JAN 21 @leshghi @esterzhao 
- [x] Review Ester's code (if time)
- [x] Create the Config sidebar in the UI
- [x] Create a +/- functionality that links with the AnalysisConfiguration/AnalysisRequests objects, so that you can make a new one and switch between them
- [x] Add in AnalysisResults underneath AnalysisConfigurations

**Comment by leshghi** [comment]
Completed a very (very) rough draft of goals for this week. Still need to work on proper implementation with switching between results and analysis configs properly so that the graph and analysis sidebar show the correct results/values. Also lots of UI cleanup for some weird CSS things.
