### ISSUE TITLE
Create save and load button functionality for model+analysis

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#254]
* Update the UI to include a model+analysis specific save button (as opposed to model specific save)
* Work with the other teams to ensure functionality of buttons

**Comment by leshghi** [comment]
Save button created on frontend and in code review - functionality to follow.

**Comment by krhablutzel** [comment]
Save functionality added in frontend for saving model+analysis, both w/ or w/o results
