### ISSUE TITLE
Reset to a blank model UI when switching from result to config

### ISSUE THREAD

**Issue by leshghi** [amgrubb/BloomingLeaf#263]
When you first open the analysis page on a model you see a clean model with no results:
<img width="1176" alt="Screen Shot 2021-01-27 at 3 10 07 PM" src="https://user-images.githubusercontent.com/43756305/106047650-dc834380-60b1-11eb-82d2-0feec91e92be.png">
After running a simulation, results appear on the model with a slider:
<img width="1171" alt="Screen Shot 2021-01-27 at 3 11 42 PM" src="https://user-images.githubusercontent.com/43756305/106047724-f886e500-60b1-11eb-9a64-18e09ef6a308.png">
But when you switch back to a different configuration, the results are still populated on the UI:
<img width="1174" alt="Screen Shot 2021-01-27 at 3 10 23 PM" src="https://user-images.githubusercontent.com/43756305/106047774-076d9780-60b2-11eb-84f0-297b6e6dc3eb.png">

Need code to reset to the blank model UI when switching from a result to a configuration to avoid user confusion about which result is associated with which config. This does not cause any confusion in the backend or with the map, but it does impact the user experience and should be fixed asap.

**Comment by krhablutzel** [comment]
Just pushed updates on branch `mm-reset-ui` to hide slider, rest analysis values, and change EVO slider when switching to a configuration
