### ISSUE TITLE
Consistency of .json file between solveSinglePath and getNextState.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#27]
`{
  "analysis": {
    "currentState": "3|33",
    "initialAssignedEpoch": "TE2_14,TE1_16,TA0_0,E0001_14,TR3_66,TR5_92,E0000_16,TR4_33,TR6_60",
    "initialValueTimePoints": "0,14,16,33,60,66,92",
    "numRelTime": "4",
    "absTimePts": "",
    "elementList": [
      {
        "id": "0000",
        "status": [
          "0011",
          "0011",
          "1100",
          "1100",
          "1100",
          "1100",
          "1100"
        ]
      },
      {
        "id": "0001",
        "status": [
          "1100",
          "0011",
          "0011",
          "0011",
          "0011",
          "0011",
          "0011"
        ]
      }
    ],
    "getNextState": true,
    "solveSinglePath": false,
    "maxAbsTime": "100",
    "conflictLevel": "W"
  },`

....

`    "allStatesModel": [
      {
        "intentionElements": [
          {
            "status": [
              "1100"
            ],
            "id": "0000"
          },
          {
            "status": [
              "0011"
            ],
            "id": "0001"
          }
        ],
        "time": 0
      }
    ]
  }
}`

Why are the values stored in elementList and not allStatesModel.
There seems to be a lot of duplications in this file, perhaps we can simplify it.

[default.txt](https://github.com/amgrubb/BloomingLeaf/files/1242415/default.txt)

**Comment by amgrubb** [comment]
We should remove either elementList or allStatesModel.
The values should be stored in the same place for both find single path and find all possible next states.

**Comment by Akira83** [comment]
Removed the allStatesModel, all information that this variable contains should be in the element list.

**Comment by Akira83** [comment]
I will close this issue.
