### ISSUE TITLE
Cannot Use EVO on Loaded Results

### ISSUE THREAD

**Issue by ibrodycalixto** [amgrubb/BloomingLeaf#280]
After loading saved results, user can't use EVO color visualization on those results.

**Comment by krhablutzel** [comment]
I might be able to fix this with Kate and Megan on Wednesday when we look at refreshing EVO when clicking different results.

**Comment by krhablutzel** [comment]
Met w/ Megan and Kate, and this turns out to be a larger project that they'll tackle over the next few weeks.
