### ISSUE TITLE
Redo breaks for adding new intentions to actors

### ISSUE THREAD

**Issue by YesugenB** [amgrubb/BloomingLeaf#288]
When the user adds a new intention within an actor, clicks 'Undo' and then attempts to Redo it, the intentions do not return. 

To Replicate: 
1. Load a model that contains actors/add an actor to the model
2. Add two intentions within an actor 
3. Add a link 
4. Undo the two intentions and link
5. Redo

Before: 
<img width="1440" alt="Screen Shot 2021-03-03 at 8 32 29 AM" src="https://user-images.githubusercontent.com/59470488/109813254-18eb1780-7bfb-11eb-8ef7-d6fee8d3fc07.png">

After: 
<img width="1440" alt="Screen Shot 2021-03-03 at 8 32 49 AM" src="https://user-images.githubusercontent.com/59470488/109813285-256f7000-7bfb-11eb-8c05-b987e3ffc7c6.png">

When you press 'Redo', the intentions do not appear but a link is added with nothing to go between.

**Comment by amgrubb** [comment]
@Domily11 Can you test this to see if it is still an issue?

**Comment by YesugenB** [comment]
Related to #552?
