### ISSUE TITLE
Adding new intentions is broken for loaded model with results

### ISSUE THREAD

**Issue by krhablutzel** [amgrubb/BloomingLeaf#289]
If the user loads a model that contains results, adding intentions breaks in multiple ways. For example, if the user drags a goal into the model, the user will continue adding goals everywhere they click on the paper until they click back into the drag-and-drop template. These new intentions cannot be moved, and throw multiple TypeErrors where `analysisRequest.getUserEvaluationByID is not a function`.

To replicate:
1. Load a model with results
2. Drag a goal onto the paper
3. Click elsewhere on the paper - goals keep getting added
4. Click back into the drag-and-drop template - goals stop adding wherever the user clicks
5. Try to move a goal that was just added - it won't move

Example:
<img width="1438" alt="Screen Shot 2021-03-03 at 09 07 48" src="https://user-images.githubusercontent.com/59173829/109817451-f3144180-7bff-11eb-8401-166c0031c27d.png">

This is likely related to other errors that have been showing up in model management related to AnalysisRequests in loaded models.

Results also remain after the model is changed, but this is likely another model management feature that still needs to be added.

**Comment by leshghi** [comment]
@krhablutzel Did you fix this in a prior pull request? I feel like I remember you merging a fix but am unsure.

**Comment by krhablutzel** [comment]
You're right, I did! This was a symptom of issue #290 where the loaded analysisRequest was not an instance of the AnalysisRequest class, and thus didn't have its methods. This should be fixed with #290; I'll close it now!
