### ISSUE TITLE
Get Possible Next states doesn't work 

### ISSUE THREAD

**Issue by fsam95** [amgrubb/BloomingLeaf#3]
Steps to reproduce: 
- Create one goal intention and two task intentions
- Have one task partially contribute to the denial of the goal (+D) and the other one partially contribute to the satisfaction of the goal (+S)
- Set the initial satisfaction of both tasks to be Fully Satisfied
- Click the "Get Possible next states button"

Expected: Goal should be (PS, PS) (or (PD,PD)?)
Actual: Goal is (FS, T)

**Comment by Akira83** [comment]
I'm getting this BUG when executing this case. I don't know if it is a valid test, if it is not we should warn the user for this invalid input.

[BUG.txt](https://github.com/amgrubb/BloomingLeaf/files/1263985/BUG.txt)

**Comment by Akira83** [comment]
Tested the execution in localhost and it is working.
The problems were the flags that changed, now there is only one flag that call action which contains the type of analysis that will be executed.
Need to be test on server.

**Comment by Akira83** [comment]
I'm getting a different error to solve Single Path now.

**Comment by amgrubb** [comment]
Yeah, it's something to do with the change for the allNextState.

**Comment by amgrubb** [comment]
Problems should be incorporated into #59.
