### ISSUE TITLE
Saving some graph values

### ISSUE THREAD

**Issue by Akira83** [amgrubb/BloomingLeaf#30]
Some values of the graph like constraints, function type... are not being saved properly or not being reload when you load the file.

**Comment by Akira83** [comment]
I think that I discovered why this is happening.
When we ask for the jointjs load a graph from a saved json it only loads the original attributes from the graph (similiar to what the GSON library does). So the new attributes that we add to the graph are not loaded even thought they are saved.

Possible solution:
- Load with the jointjs as it is being done.
- After that, read the json file and add all known attributes again to the current graph object.

**Comment by amgrubb** [comment]
@Akira83 what is the status of this bug?

**Comment by amgrubb** [comment]
After testing, it appears to be resolved. If it comes up again, we can reopen.
