### ISSUE TITLE
Configs are being covered by the watermark and cannot be accessed

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#315]
<img width="611" alt="Screen Shot 2021-03-26 at 11 30 58 AM" src="https://user-images.githubusercontent.com/37080292/112655550-e19d0e80-8e26-11eb-8a18-964ad5742a06.png">
* Need to either add a scroll bar or make the watermark its own div that cannot overlay the config sidebar div

**Comment by leshghi** [comment]
Ask in meeting 3/28 about potentially moving watermark - otherwise it needs its own div even with scrollbar
