### ISSUE TITLE
Sample models that do not work 

### ISSUE THREAD

**Issue by YesugenB** [amgrubb/BloomingLeaf#317]
The sample models: 
-game before.json
-media shop before.json
-medical before
-toll before
give the following error when a user tries to Explore Next States with various Conflict Prevention Levels and Num Relative Time Points
<img width="533" alt="Screen Shot 2021-03-29 at 5 25 58 AM" src="https://user-images.githubusercontent.com/59470488/112816294-3fac3a80-904f-11eb-9ba6-b0b5bbf6cbc9.png">

-spadina opp.json gives "RuntimeException: TroposCSPAlgorithm: Dynamic type not found for Goal_3" when you try to Simulate Single Path
-spadina pro.json gives "RuntimeException: null" when you try to save & close from Explore Next States

**Comment by YesugenB** [comment]
The sample v2-models give an error:

- game before
- gate before 
- media shop before
- medical before 

![image](https://user-images.githubusercontent.com/59470488/132959453-527da6e7-54ba-478b-885f-327ad7ea3f01.png)

**Comment by amgrubb** [comment]
All issues are for next state...revisit later.
