### ISSUE TITLE
General CSS bugs

### ISSUE THREAD

**Issue by krhablutzel** [amgrubb/BloomingLeaf#326]
Intending this to be a place to compile CSS bugs to fix at a future date.

- [x]  I can scroll down on the webpage because the analysis inspector panel is too long. (Sometimes I can scroll side-to-side, too, especially in a smaller window.)
- [x]  The watermark overlaps the config scroll box/the actors when the webpage gets shorter.
- [x]  We need to update the watermark with Smith info
- [x]  Could we auto-scroll to where new results are added? Or else add a less shadow-y line at the bottom of the scroll box so the user can see it's scrolling.
- [x]  Larger EVO slider overlaps the View Assignments List button

**Comment by amgrubb** [comment]
@Manarnz Can you check off, whichever ones you've already completed.

**Comment by krhablutzel** [comment]
- changed stencil scroll box to stop above the watermark/attribution box, so attribution doesn't overlap stencil elements
- investigated auto-scrolling to where new results are added; decided this would be overcomplicated
- verified that other listed bugs appear to be fixed
