### ISSUE TITLE
Create Backbone.js training materials

### ISSUE THREAD

**Issue by leshghi** [amgrubb/BloomingLeaf#335]
Need materials to introduce the current and new lab members to backbone.js and its use cases for this codebase

**Comment by leshghi** [comment]
Working on [Google Doc](https://docs.google.com/document/d/1wnJlPZLH0HuUheInG7MVXaQfYZHSo9LOwTfgtadBJYc/edit?usp=sharing) to compile content - will later transfer into markdown.

**Comment by amgrubb** [comment]
Great job everyone.
