### ISSUE TITLE
Missing Files from index.html

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#34]
Files removed in #31 but they are still used by index.html or included there?
![screen shot 2017-08-24 at 3 57 10 pm](https://user-images.githubusercontent.com/6596937/29685916-f5750ed0-88e4-11e7-8ac0-4ea5d3aa7899.png)

**Comment by Akira83** [comment]
This files were removed when I merged the allStatesModel into elementList.
Already removed from index.html
