### ISSUE TITLE
Loaded links don't change source/target

### ISSUE THREAD

**Issue by krhablutzel** [amgrubb/BloomingLeaf#344]
In models loaded from JSON, links don't change source or target when dragged to a new intention. This relates to the `cell.on("change:target",` and `cell.on("change:source"` events in `createLink()` within onFunctions.js, because `cell.on(` event listeners only appear to be added to links created with `createLink()`, not links loaded from JSON.

**Comment by amgrubb** [comment]
@Domily11 Confirm if fixed and close.
