### ISSUE TITLE
Include all fields in transfer file even if they are not needed?

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#35]
I think that all the fields should be listed even if they are not used.
For example in this file "absTimePts":"" is missing.
![screen shot 2017-08-24 at 4 05 04 pm](https://user-images.githubusercontent.com/6596937/29686204-1b5ad7c8-88e6-11e7-818d-b7398c00a5ca.png)

Open to discussion.

**Comment by Akira83** [comment]
I will add all fields. The ones that are not being used will have the null value.

**Comment by Akira83** [comment]
I will close it for now.
