### ISSUE TITLE
Migrate slider methods from displayAnalysis into object/viewObjects.js/SliderObj class

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#368]
<img width="739" alt="Screen Shot 2021-05-14 at 10 54 21 AM" src="https://user-images.githubusercontent.com/37080292/118288900-cf446600-b4a2-11eb-83dc-2a65a3d92f12.png">

Methods in displayAnalysis.js such as createSlider(), etc, can become class methods for the SliderObj. Migrate methods into the SliderObj class and fix any bugs that occur. 

Additionally -- finish updating SliderObj docstrings and evaluate the object type of all params

**Comment by esterzhao** [comment]
<img width="739" alt="Screen Shot 2021-05-14 at 10 54 21 AM" src="https://user-images.githubusercontent.com/37080292/118288900-cf446600-b4a2-11eb-83dc-2a65a3d92f12.png">

Methods in displayAnalysis.js such as createSlider(), etc, can become class methods for the SliderObj. Migrate methods into the SliderObj class and fix any bugs that occur. 

Additionally -- finish updating SliderObj docstrings and evaluate the object type of all params

**Comment by amgrubb** [comment]
@Domily11 confirm whether this is fixed.
