### ISSUE TITLE
linkSrcID and linkDestID are incorrectly assigned for the Intentionlink and Actorlink in joint.extensions.js

### ISSUE THREAD

**Issue by leshghi** [amgrubb/BloomingLeaf#390]
As part of our switch to using the graph cells to store our model data, linkSrcID and linkDestID were added as parameters to the Intentionlink and Actorlink objects. However, for some reason they always appear to be one off (for example, if the source nodeID is 0000, the linkSrcID will show as 0001). See onFunctions.js ~780 to see where they should be assigned. Explore the code/use console logs to see why and how to fix it. 

Some other lines that may be helpful that I have briefly looked into as the cause: onFunctions.js ~390 (are intention ids being reassigned and that is why they are wrong?).

**Comment by Domily11** [comment]
Do we still need to do this? We don't need to assign and linkSrcID or linkDestID anymore

**Comment by leshghi** [comment]
> Do we still need to do this? We don't need to assign and linkSrcID or linkDestID anymore

No we do not! Great catch - I'll close it
