### ISSUE TITLE
Using the .remove() so ActorInspector doesn't get called multiple times on screen

### ISSUE THREAD

**Issue by Manarnz** [amgrubb/BloomingLeaf#401]
When we implemented the model in actorInspector.js, we faced an issue with rendering the actor icon from graph, as it would not stop creating actor icons. We then proceeded to delete the actorInspector.clear() and we faced another issue: every time we change the actor's icon the side bar would another name and type inputs. we are suspecting that this bug was created during the process of turning ActorInspector.js into backbone.

**Comment by Manarnz** [comment]
When we delete ActorInspector.clear(): 
<img width="842" alt="Screenshot 2021-06-11 171557" src="https://user-images.githubusercontent.com/83615524/121749482-bbf3dd00-cad8-11eb-8305-d6f3e0aef140.png">

**Comment by Domily11** [comment]
I also previously tried putting this.remove in render, just to see what it does. The Inspector does not show up at all

**Comment by angelac2023** [comment]
Irene and I are having this same issue for intentions

**Comment by Manarnz** [comment]
When we add ActorInspector.clear() 
<img width="677" alt="Screenshot 2021-06-11 171819" src="https://user-images.githubusercontent.com/83615524/121749704-1e4cdd80-cad9-11eb-9315-37b8773f873f.png">
