### ISSUE TITLE
Error reading results into analysis.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#43]
There is an error reading correct results into the front-end.
See the screen shot below. The eclipse results are on the left.
![screen shot 2017-08-26 at 2 23 51 pm](https://user-images.githubusercontent.com/6596937/29744061-c9e2db26-8a6a-11e7-9186-6b0fb4fc2865.png)

**Comment by Akira83** [comment]
Alicia could you send the output.out file that generates this error?

**Comment by amgrubb** [comment]
Sure it in the screenshot on the left.
Hopefully this works...

Output:
{
  "elementList": [
    {
      "id": "0000",
      "status": [
        "0000",
        "0011",
        "0100",
        "0010",
        "1100",
        "1100",
        "1100"
      ]
    },
    {
      "id": "0001",
      "status": [
        "0000",
        "0011",
        "0100",
        "0010",
        "1110",
        "1110",
        "0110"
      ]
    },
    {
      "id": "0002",
      "status": [
        "0011",
        "0011",
        "0011",
        "0011",
        "1100",
        "1100",
        "1100"
      ]
    }
  ],
  "allSolution": [
    
  ],
  "finalAssignedEpoch": [
    "TA0_0",
    "TE3_49",
    "TA2_6",
    "E0002_49",
    "TA1_4",
    "TR5_32",
    "TR4_64",
    "TR6_72"
  ],
  "finalValueTimePoints": [
    "0",
    "4",
    "6",
    "32",
    "49",
    "64",
    "72"
  ],
  "relativeTimePoints": 3,
  "absoluteTimePoints": [
    4,
    6
  ]
}

[default.txt](https://github.com/amgrubb/BloomingLeaf/files/1253926/default.txt)
[output.txt](https://github.com/amgrubb/BloomingLeaf/files/1253927/output.txt)

**Comment by Akira83** [comment]
That is strange... when I execute this file it is working fine here... I will investigate more.

**Comment by Akira83** [comment]
Sorry... if you are trying to execute this on the web I forgot to update the backend.js to run on web.

**Comment by amgrubb** [comment]
Thanks, we need to document all these flag variables in the project! I'm just not sure where the best place to list them is.

leaf-ui/js/backend.js  <-- `var localhost = true;`
true for local, false when on server.
 
I think in the interim, we might actually want to show what goes to the server for testing:
`console.log(JSON.stringify(js_object));`

Question: When `localhost = true` does that load results from a file, can I simulate results locally? If so, how? (Another thing that should be documented.)

**Comment by Akira83** [comment]
To simulate the results locally you need to get the content of output file and paste in the analysisResults variable.

console.log(JSON.stringify(js_object)); 
==> analysisResults = {};

	if(localhost){
		//Show in console just to see what is going to backend
		console.log(JSON.stringify(js_object));
		analysisResults = {};
		
		loadAnalysis(analysisResults);
		var currentValueLimit = parseInt(sliderObject.sliderElement.noUiSlider.get());

Then you will have to update the page (press F5) and press the analysis button again.
It is a little bit work but I think it is better sometimes than executing on server
