### ISSUE TITLE
Absolute value table still contains goals without dynamics.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#44]
The absolute value table for this model, should not contain "NT" types, specifically Have Bike Lanes and Build Bike Lanes.

![screen shot 2017-08-27 at 11 35 42 am](https://user-images.githubusercontent.com/6596937/29751483-e28ccb44-8b1b-11e7-8b7a-abdff03b8343.png)

![screen shot 2017-08-27 at 11 21 33 am](https://user-images.githubusercontent.com/6596937/29751473-bd7ff538-8b1b-11e7-801f-9e955502db85.png)

**Comment by g2hchang** [comment]
Bug appears to be fixed.

**Comment by amgrubb** [comment]
The bug is not fixed yet. @g2hchang 
Can you look at this again.

**Comment by Akira83** [comment]
Agreed! If we see the bug again we reopen this issue!
