### ISSUE TITLE
UD won't allow Decrease (D) to have value.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#45]
When I create the following function. I can't select anything in the box next to Decrease. I should be able to select an evaluation label.

![screen shot 2017-08-27 at 11 19 01 am](https://user-images.githubusercontent.com/6596937/29751501-4605f5d8-8b1c-11e7-86d3-8c75f7c5073c.png)

**Comment by g2hchang** [comment]
Created a pull request #54
