### ISSUE TITLE
UD Functions not sent to backend correctly?

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#46]
test (4).json is the model I am currently working with.
If I delete the UD function then I can run Simulate Single Path no problem.
With the UD function, I am getting the following error.

![screen shot 2017-08-27 at 11 30 36 am](https://user-images.githubusercontent.com/6596937/29751574-5355d770-8b1d-11e7-8175-e3c80d45b477.png)
[test (4).json.txt](https://github.com/amgrubb/BloomingLeaf/files/1254497/test.4.json.txt)

**Comment by Akira83** [comment]
This seems to be an issue already corrected.
