### ISSUE TITLE
Repeating User-Defined Absolute Time Entry.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#47]
The definition of a repeating function states:
> Let a goal g ∈ G, and a sequence of atomic functions A be given, where ai ∈ A is the tuple ⟨goal, type, x, start, stop⟩ and ∀ai ∈ A : ai(goal) = g ∧ ai(stop) = ai+1(start). A repeating compound function is the tuple ⟨g, A, repNum, absTime⟩, where g is the given goal, A is the given set of atomic functions, repNum ∈ N+ is the number of repeats for the entirety of A, and absT ime ∈ N0 is the time between repeats or zero if no value is specified. A repeating compound function is a sequence of atomic functions over disjoint neighbouring intervals that repeat repNum to define how the evaluation of goal g changes over the time.

We need to give the user a way of specifying repNum, absTime.

Perhaps in the function definition here:
![screen shot 2017-08-27 at 11 20 43 am](https://user-images.githubusercontent.com/6596937/29751644-23dbfb90-8b1e-11e7-80bc-e4764b78e1c6.png)
Or perhaps in the absolute values table here:
![screen shot 2017-08-27 at 11 21 33 am](https://user-images.githubusercontent.com/6596937/29751658-536287ee-8b1e-11e7-9ac9-bf256a08cde3.png)

**Comment by Akira83** [comment]
I think that it would be more convenient for the user if this options are set in the Function definition panel, otherwise the user can be lost on where to define this kind of information. But it is just my opinion...

**Comment by amgrubb** [comment]
Yes, but we need to keep all the absolute value together.

**Comment by amgrubb** [comment]
I now agree with @Akira83. The absolute number and number of repeats should be set on the element panel. 

1. We need to add the following change (see screen shot).
![screen shot 2017-10-20 at 9 29 52 pm](https://user-images.githubusercontent.com/6596937/31846883-a9b1f4fe-b5df-11e7-970a-037ef6f4aaad.png)

2. In the Absolute and Relative Assignments table, we need to disable the values that are in the repeating segment. For example, in the Bike Lane Usage example above, we need to disable time points B, C, and D. Because they are in the repeating part.

@g2hchang Can you make these changes?

**Comment by g2hchang** [comment]
Created a pull request #112

**Comment by g2hchang** [comment]
Pull request #112
