### ISSUE TITLE
Dynamic Function Marked Value doesn't save.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#5]
Done of the marked values (the satisfaction value used in the dynamic function) are saving when you select them in the interface. They are returning to the default.

This includes: MP, MN, and RC.
![screen shot 2017-08-14 at 1 36 45 pm](https://user-images.githubusercontent.com/6596937/29285442-84a8402c-80fc-11e7-93bf-7b6ce32cc47f.png)

This results in incorrect or missing marked values in the backend.

**Comment by Akira83** [comment]
Fixed in frontend, not verify if the correct value is going to backend. This one was a bit hard to fix, it took more time to find where change the code.

**Comment by Akira83** [comment]
I will not create a pull request for this because when I tried to create a new pull request it creates with the previous commits that I did. So I will wait until the previous pull request is finished. Then I submit this new one.

**Comment by amgrubb** [comment]
Previous pull request was approved.

**Comment by Akira83** [comment]
I will close this issue, if the problem reaper we open it again.
