### ISSUE TITLE
Error sometimes appears when first loading website

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#538]
![image](https://user-images.githubusercontent.com/72589318/129040194-baebe822-af33-48b6-888f-209fe4441b88.png)

**Comment by amgrubb** [comment]
What branch were you on when this error occurred?

**Comment by i-m-foster** [comment]
> What branch were you on when this error occurred?

It was on yib-nextState but I haven't seen it since we pulled from backbone-refactor so it's possible it has been fixed
