### ISSUE TITLE
All Next State Issues Combined

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#549]
Combines Issue #328 (Explore Next States doesn't save as result), issue #331 (User can click buttons while the next states window is loading), Issue #332 (Explore Next States Window: Delay between selecting a filter and appearing as checked on the box), and Issue #514 (Converting Explore Next States into Backbone.js)

**Current To Do List**
- [x] Implement last three check boxes (least actor, most actor, and most constrained satisfied)
- [x] Fix Actor so you can open next State with an actor
- [x] Fix unclick checkbox functions
- [x] Make it so you can't open next state from last time point
- [x] Make it so you can’t click buttons while next state is loading 
- [x] Add spinner back while waiting for next State 
- [x] Implement save button in next State
- [x] Implement explore next State buttons and add spinner
- [x] Add spinner for delay between selecting a filter and appearing as checked on the box
- [x] Make it so you can’t run next State if you havent simulated single path yet
- [x] Allow option to cancel next State from loading
- [x] Change color of spinner to blue (low-priority) 
- [x] Fix logic of actor filters
- [x] Make it so you cant open more next State windows than time points
- [x] Fix save button in next State

**Comment by amgrubb** [comment]
Depends on #522.
