### ISSUE TITLE
Undo causing error in commander

### ISSUE THREAD

**Issue by Domily11** [amgrubb/BloomingLeaf#552]
Currently, whenever we click on undo right after adding a new element on the graph, there is an error that occurs for everything except a normal link between intentions. This error seems to be happen because "add" is supposed to be the first function to be called, but for some reason "chang:intention/link" is actually the first to be called, causing an error in commander.js

**Comment by amgrubb** [comment]
Possible Change (in Rappid version 2.3.1): 

> Go to BloomingLeaf/leaf-ui/rappid/dist/joint.dia.command.js
> Change line 430 to be `insertPosition = 0`

**Comment by bobiamack** [comment]
screenshot of the error 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/98605251/216850838-6038ccb0-bbc0-449c-81fb-8b03e106d4fa.png">
