### ISSUE TITLE
Error: <path> attribute d bug

### ISSUE THREAD

**Issue by g2hchang** [amgrubb/BloomingLeaf#56]
Whenever the elements are created and click on link icon, Chrome inspector throws jquery.min.js:5 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "0" error.

**Comment by g2hchang** [comment]
Apparently, the error appears on Chrome and Safari, but not in Firefox. I need a further investigation on this issue.

**Comment by oibrahim22** [comment]
We have not attempted to fix this bug
