### ISSUE TITLE
EVO Automatically Turned On

### ISSUE THREAD

**Issue by YanningTan** [amgrubb/BloomingLeaf#565]
If we switch to the analysis mode, click ‘back’ button on Chrome, and then return to the BloomingLeaf, EVO would be automatically turned on.
![WechatIMG287](https://user-images.githubusercontent.com/59700167/132705871-6d4e7efa-9b07-4263-98eb-5ca6c460bd7a.jpeg)

**Comment by YesugenB** [comment]
Alicia said that the back/forward button is not the issue, but loading a model while EVO is turned on is.
