### ISSUE TITLE
Intermediate Values Table at the bottom is cut off when viewing

### ISSUE THREAD

**Issue by Vbeany** [amgrubb/BloomingLeaf#571]
Only for a couple of models: When viewing the Intermediate Values Table with lots of info and scrolling down to look the last row is cut off from view
(Screenshot from vendor model)
![Cut off](https://user-images.githubusercontent.com/89676581/132960710-c9cf62f7-5db6-4838-9744-4fc5d7325a3a.png)

**Comment by Domily11** [comment]
Not sure if this is still relevant as this problem is not showing up for me
