### ISSUE TITLE
Add Buttons to AllPaths popup.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#59]
We need the following buttons:
Accept Current State and Save- takes the current state (and any previous) and adds it to the path generated. (Call single path with values up to the current state.)
Accept Current State and Generate All Next States - stores the current state and then generates the next state.
Close - reject current path and close window.

**Comment by Akira83** [comment]
Button Close current path done.

**Comment by Akira83** [comment]
Accept Current State and Save.
Questions:
In the original analysis (Single Path) I have the following result:
`{
  "elementList": [
    {
      "id": "0000",
      "status": [
        "0000",
        "1110",
        "1110",
        "1110",
        "1100",
        "1110"
      ]
    }
  ],
  "allSolution": [
    
  ],
  "finalAssignedEpoch": [
    "TA0_0",
    "TR1_12",
    "TR3_10",
    "TR2_11",
    "TR5_61",
    "TR4_91"
  ],
  "finalValueTimePoints": [
    "0",
    "10",
    "11",
    "12",
    "61",
    "91"
  ],
  "relativeTimePoints": 5
}`

Then I need to add the result from pop up which is something like this:
`"intentionElements": [
        {
          "id": "0",
          "status": [
            "1110"
          ]
        }
      ]`

My question is what should be the values for finalAssignedEpoch and finalValueTimePoints. I will need to add some values there or the length of each vector is going to be different from the elementsList.

**Comment by amgrubb** [comment]
@Akira83 In the example above in your original simulation, you have only one intention and 5 relative steps, right?

In order to select the next state, we need to ask the user which of the remaining time points they want to apply.

We should meet in person to discuss this.

**Comment by amgrubb** [comment]
- [ ] Create algorithm for resolving time points from All Paths analysis.
Figure out how to determine what the next time point is.
Can we give the user choices.
< Merged with #60 >

**Comment by amgrubb** [comment]
Here is the summary of our meeting today. Let me know if you have any questions.

In the pop up window where the states are displayed, we should also show:
`Path Length`, `Current Step`, `Previous Time`, `Max Time`.

There are three types of time points:
1. Absolute
2. Relative
3. EB Time Points (from intentions and relationship...and may have an absolute value associated).

Once the user clicks `Accept Current State` a small pop up should appear to the user can assign a time point to the current state.

Show all non-assigned EBs in two groups: 1. Those the user can pick, 2. Future time points that cannot be assigned to the current state. 
For the relative time points (and EBs without an absolute time point), allow the user to pick a time within the allowable range.

For EB time points, you have to check wether the state that the user picked has transitioned per the EB requirements.
For example, consider a one goal (with a SD function) and with 5 relative time points, if the user picks the value FS for the goal than the time point can be one of the relative points, but if the user picks FD, then it has to be the EB for the goal.

You also need to consider the constraints between EB, which is part of #87.

Let me know if you have any questions.

**Comment by Akira83** [comment]
`{
  "analysis": {
    "action": "allNextStates",
    "maxAbsTime": "100",
    "conflictLevel": "S",
    "numRelTime": "5",
    "absTimePts": "6",
    "currentState": "3|79",
    "initialAssignedEpoch": [
      "TA0_0",
      "TR3_81",
      "TA1_6",
      "TR2_79",
      "TR5_83",
      "TR4_50",
      "TR6_95"
    ],
    "initialValueTimePoints": [
      "0",
      "6",
      "50",
      "79",
      "81",
      "83",
      "95"
    ],
    "elementList": [
      {
        "id": "0001",
        "status": [
          "1110",
          "0100",
          "0100",
          "0011"
        ]
      },
      {
        "id": "0001",
        "status": [
          "1110",
          "0100",
          "0100",
          "0011"
        ]
      }
    ]
  },
  "model": {
    "actors": [
      
    ],
    "intentions": [
      {
        "nodeActorID": "-",
        "nodeID": "0000",
        "nodeType": "G",
        "nodeName": "Goal_0"
      },
      {
        "nodeActorID": "-",
        "nodeID": "0001",
        "nodeType": "G",
        "nodeName": "Goal_1"
      }
    ],
    "links": [
      {
        "linkType": "AND",
        "linkSrcID": "0001",
        "linkDestID": "0000",
        "postType": null,
        "absoluteValue": -1
      }
    ],
    "dynamics": [
      {
        "intentionID": "0000",
        "dynamicType": "NT",
        "markedValue": "0011",
        "line": null
      },
      {
        "intentionID": "0001",
        "dynamicType": "NT",
        "markedValue": "0011",
        "line": null
      }
    ],
    "constraints": [
      
    ]
  }
}`

@amgrubb , I'm trying to execute this all next steps but I'm getting this as console output:

N0000_0_PS::0
N0001_0_PS::1
Constraint: AndBoolVector2 : andBool([ N0001_0_PS=1], N0000_0_PS=0)
have conflicting constraints, not solvable

Is this correct?

The model is this:
![bug](https://user-images.githubusercontent.com/5030821/32293348-2c4f2dcc-bf19-11e7-8ef4-7f76f196335b.png)

**Comment by amgrubb** [comment]
Yes, this is a bug, I created a hotFix branch of your branch.

**Comment by amgrubb** [comment]
The problem is the id of both elements in the elementList is "0001" (see below).
@Akira83 I didn't generate this result. Can you look into why the output is wrong, or was it just a typo in your example?

`"elementList": [
{
"id": "0001",
"status": [
"1110",
"0100",
"0100",
"0011"
]
},
{
"id": "0001",
"status": [
"1110",
"0100",
"0100",
"0011"
]
}
]
},`

**Comment by Akira83** [comment]
Well I was going to check the output... but now I'm getting this:

Error: The length of initialValueTimePoints and initialValues[0] do not match.

**Comment by Akira83** [comment]
I pull the alterations and I'm running in:
http://www.cs.utoronto.ca/~marcel/BloomingLeaf/leaf-ui/

Sometimes I am able to run the "Explore Possible Next States" but most of the times I'm getting constraints errors.

**Comment by Akira83** [comment]
@amgrubb 
I have created a modal to show when the save button is pressed.
http://www.cs.utoronto.ca/~marcel/BloomingLeaf/leaf-ui/

In this modal I added all the data available that I can modify for now. In this data there are 4 objects:
- SinglePathAnalysis: data sent to analysis
- SinglePathResults: data received from backend
- NextStatesAnalysis: data sent to NextStates analysis
- NextStateResults: data received from backend
The JSON is also printed in the console.

Could you identify which data do you want me to show for the user? Or if should have any other data in this modal that is not there.

**Comment by amgrubb** [comment]
Hi @Akira83,
I now understand your questions (sorry for the delay).
You said you created an example. My issue is that I don't see any of the example files at: http://www.cs.utoronto.ca/~marcel/BloomingLeaf/leaf-ui/.

Do you have the sample files? Are they located somewhere on your website?

**Comment by amgrubb** [comment]
The single result that was selected from the `NextStateResults` should be added to the `SinglePathResults` to create a new single path, based on the result that was added.
Actually, you should be able to update `NextStatesAnalysis' with the additional state.

Should we meet to discuss this?
