### ISSUE TITLE
Increase / Decrease should not have marked value.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#6]
The satisfaction label box should not appear for Increase or Decrease (the bottom on in the screen shot). The marked value is FS and FD respectively for passing to the backend. 
![screen shot 2017-08-14 at 1 40 31 pm](https://user-images.githubusercontent.com/6596937/29285556-de1cb75a-80fc-11e7-8d49-0f8b831938da.png)

**Comment by Akira83** [comment]
If I understood correctly it should be like this:
![increase](https://user-images.githubusercontent.com/5030821/29374891-09dab452-8281-11e7-8c1f-0f3a3ee0bd14.jpg)
![decrease](https://user-images.githubusercontent.com/5030821/29374896-0cb465f6-8281-11e7-9e24-93e85bece695.jpg)

**Comment by amgrubb** [comment]
Yes that is correct.

**Comment by amgrubb** [comment]
Updated Online

**Comment by amgrubb** [comment]
I screwed up, this isn't actually a bug and was correct in the first place.
Can we undo the pull request?

**Comment by amgrubb** [comment]
Some of this code was useful, so we need to figure out what to keep.

**Comment by amgrubb** [comment]
I reverted the change, and now none of the market values are saving properly.
I don't see how any of these changes affect that.

**Comment by Akira83** [comment]
I will close this issue. If the problem reaper we open it again.
