### ISSUE TITLE
Setting num rel time point to 0 

### ISSUE THREAD

**Issue by YesugenB** [amgrubb/BloomingLeaf#610]
Setting num rel time point to 0 and then simulating single path gives this error. 
<img width="1920" alt="Screen Shot 2021-10-29 at 4 21 15 PM" src="https://user-images.githubusercontent.com/59470488/139497123-a3a593bd-df86-4f71-9a9d-00d09da90cfa.png">

**Comment by Domily11** [comment]
@amgrubb How is the rel time supposed to act when it's set at 0?

**Comment by Cyrine-BA** [comment]
I found on nouislider.min.js the following code:
"if(b.min===b.max)throw new Error("noUiSlider: 'range' 'min' and 'max' cannot be equal.")"
So I am guessing min and max are 0 here? 
Also, the number you're plugging in is the number of "stops of the slider" if that makes sense, so I think it's not a problem.

**Comment by YanningTan** [comment]
> I found on nouislider.min.js the following code: "if(b.min===b.max)throw new Error("noUiSlider: 'range' 'min' and 'max' cannot be equal.")" So I am guessing min and max are 0 here? Also, the number you're plugging in is the number of "stops of the slider" if that makes sense, so I think it's not a problem.

We found that this is because the nov21-bug branch has not been merged yet.
