### ISSUE TITLE
If you have an intention selected, you can't clear the evaluation label after you clear dynamic label

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#613]
This is because while clear dynamic label clear the function text in the intention, it does not clear the function-type in the element inspector. It should be fixed by rerendering/updating html for element inspector

**Comment by mvarnum** [comment]
Steps to recreate:
1. Add an intention to the model, and assign it a function and satisfaction value:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/55264239/216851283-b52a439e-c2a2-4ac1-a16d-f3e08c8dbac0.png">

2. Clear Dynamic Function Labels:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/55264239/216851306-240b066b-8389-40c9-a30a-db5085212ef3.png">

3. CLICK OFF THE INTENTION (the bug only appears when the intention is not selected) and select Clear Evaluation Labels:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/55264239/216851370-158c58df-4c11-4c36-b5d6-cde2d3832109.png">

4. The model view does not refresh and this error shows in the console:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/55264239/216851412-79fb00fa-d0b8-442d-b3f8-5c6baafb9423.png">
