### ISSUE TITLE
Intention doesn't change color in EVO when initially assigned NB

### ISSUE THREAD

**Issue by Domily11** [amgrubb/BloomingLeaf#614]
The intention doesn't change color even though it has a satisfaction value when you first turn on EVO then drag a link in between two intentions and change the link to not both (either one is fine) 
![image](https://user-images.githubusercontent.com/47505178/141191168-4e055c4c-a870-4408-8b78-47ca99cf7639.png)

**Comment by Domily11** [comment]
Also, @amgrubb is the two NBs supposed to have different satisfaction values? Right now they have the same ones

**Comment by amgrubb** [comment]
> Also, @amgrubb is the two NBs supposed to have different satisfaction values? Right now they have the same ones

Only after the transition point. They should both be None prior to the transitions, then one is Satisfied and the other is Denied [resp. None] if it is NBD [resp. NBN].
