### ISSUE TITLE
EVO Choose-Your-Own-Colors

### ISSUE THREAD

**Issue by Domily11** [amgrubb/BloomingLeaf#618]

**Comment by YanningTan** [comment]
Current Tempted Proposal
SetUp
Hex: rrggbb, which are actually three numbers in hex.
None: #ffffff (255,255,255) white
Formula:
              Input: the hex color code of Satisfied/Denied
              
             Calculate Partially satisfied/Denied:
                    Keep the largest value of the three 
                   13/14* (second largest value+⅔(255-second largest value))
                    smallest+¾(255-smallest)
For Conflict Value:
//not working (to be developed
IDEA1: according to current color schema:
(P, F):    satisfied denied, max*3/4
(P, P):   (P, F), satisfied, max*2/3
(F, P):    (P, P), satisfied, max*⅔

IDEA2: Blend
Add two values/2 

Next Steps:
Go through MoDRE colorimetric presentation and paper, try to engage the concepts they introduced, and revise the plan.

**Comment by amgrubb** [comment]
@Cyrine-BA Does #694 fix this?

**Comment by Cyrine-BA** [comment]
We don't take a hex code as an input anymore according to the new EVO changes.
