### ISSUE TITLE
Rappid Update

### ISSUE THREAD

**Issue by Domily11** [amgrubb/BloomingLeaf#623]
The new version of rappid allows the website to work when you change the index.html script from 
`<script src="./rappid/node_modules/lodash/index.js"></script>` to `<script src="./rappid/node_modules/lodash/lodash.js"></script>` 

However, there seems to be a problem with communicating with the backend, because we cannot simulate a path

**Comment by YanningTan** [comment]
You also need to change the analysis.html script from
`<script src="./rappid/node_modules/lodash/index.js"></script>` to` <script src="./rappid/node_modules/lodash/lodash.js"></script>`, though this does not solve all problems.

**Comment by amgrubb** [comment]
We are not going to update Rappid at this time.
