### ISSUE TITLE
Mac commands

### ISSUE THREAD

**Issue by g2hchang** [amgrubb/BloomingLeaf#63]
Mac OS conventions for copy and paste usually start with 'command' key, but current version only accepts ctrl key. I am just proposing enhancement to support both command+c/v and ctrl+c/v if the browser is on Mac.

**Comment by g2hchang** [comment]
Pushed the proposed changes to https://github.com/amgrubb/BloomingLeaf/tree/macCommands.
@amgrubb

**Comment by amgrubb** [comment]
@g2hchang Did these changed ever get incorporated?

**Comment by amgrubb** [comment]
@Null7 Please test this and see what further extensions are required.

**Comment by amgrubb** [comment]
@Null7  Update?

**Comment by Null7** [comment]
@amgrubb Copy and paste with ctrl key does not seem to work properly on Windows. (Sorry about the late update. I slept through the day time... )

**Comment by amgrubb** [comment]
Can you see if you can fix it?

**Comment by Null7** [comment]
Commands tested, worked fine.
