### ISSUE TITLE
can only enter letters and numbers into node name

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#630]
can't add /, (, [, etc.

**Comment by YanningTan** [comment]
In ElementInspector.js, line 238`text = text.replace(/[^\w\n-]/g, ' ')`; if you comment this line out you can have these special characters as node name. I am not sure if we need this line for some special interests?

**Comment by bobiamack** [comment]
We also agree with Yanning here, should we be allowed to add special characters into node names? It seems that with line 238 being present, it is intentional to not include special characters into the title.
