### ISSUE TITLE
Undo Unfunctioning

### ISSUE THREAD

**Issue by YanningTan** [amgrubb/BloomingLeaf#631]
This problem happened with the new version of rappid.
If you put an actor on the paper, move it a bit and put an element inside it. Then move the actor a bit.  When you click undo, all elements will disappear. Afterward, if you drag a new element to the paper and click on 'undo'. There are neither response nor error messages.
<img width="1440" alt="undo problem" src="https://user-images.githubusercontent.com/59700167/152710395-147efbf3-dc4d-4446-8353-88dd31209629.png">

**Comment by sonorah** [comment]
1) Undo didn't delete everything for me in step 1. Instead, it reversed each action in backwards order (most recent to least recent). I think that's how it's supposed to be. 

2) When I dragged an element in after step 1, I was able to still remove it using undo.

Maybe I'm replicating the issue wrong; so if someone else can check as well before we close this issue, that'd be great.

**Comment by stardess** [comment]
You get the same experience as Sonora mentioned in her comment, however dragging a new element to the paper and "undo" it would not generate any outcome.
