### ISSUE TITLE
Several function types pop up even when the sat value is none

### ISSUE THREAD

**Issue by Vbeany** [amgrubb/BloomingLeaf#643]
![image](https://user-images.githubusercontent.com/89676581/157981697-c2d4d6bb-78a0-4881-894b-502f54f87c4f.png)

When I clear dynamic function labels then clear evaluation labels even when sat value is no value I can now select multiple function types when I should only be able to select the stochastic function only.

**Comment by bobiamack** [comment]
When you click the paper after clearing the evaluation labels and dynamic function labels, the function types return to only the stochastic function.
