### ISSUE TITLE
Remove Blue Button

### ISSUE THREAD

**Issue by g2hchang** [amgrubb/BloomingLeaf#65]
Remove Model Constraints and blue Button on top right corner. Refactor and remove the codes that are associated with Model Constraints functions.

**Comment by amgrubb** [comment]
Not all code will need to be removed. Some code will be used just from the new interface.
Constraints will still be send to the backend, so we need to keep a notion of constraints in the data model, but maybe we can improve how they are stored.

**Comment by amgrubb** [comment]
Consider the changes in #66 when reviewing the code to remove.

**Comment by g2hchang** [comment]
Created the pull request #70.

**Comment by amgrubb** [comment]
The button has been removed but the code still need to be refactored to remove old functionality.
