### ISSUE TITLE
Better color choices for different palettes

### ISSUE THREAD

**Issue by Domily11** [amgrubb/BloomingLeaf#651]
For the yellow-purple color palette, maybe change the text color or the shade of the yellows. Once the simulated single path has been run, it's hard to see the text. Also the lime green is pretty harsh on the eyes

**Comment by sonorah** [comment]
Can't see white text on bright yellow intention:
<img width="285" alt="Screen Shot 2022-08-01 at 1 50 27 PM" src="https://user-images.githubusercontent.com/95651905/182210978-642105fd-ba7b-4c8b-87ee-99fbb53a0297.png">

Lime green harsh on the eyes:
<img width="307" alt="Screen Shot 2022-08-01 at 1 51 19 PM" src="https://user-images.githubusercontent.com/95651905/182211133-7c75d9a7-1e01-434e-9bbe-1e0a3e0c88fb.png">

**Comment by cbenayed** [comment]
The function used for determining the text color was buggy, but it should be fixed now! (QA branch)
