### ISSUE TITLE
Double scrollers for analysis mode

### ISSUE THREAD

**Issue by Domily11** [amgrubb/BloomingLeaf#652]
After simulating a path and make the window smaller (on your own computer, without using the lab screen) the double scrollers appear again

![image](https://user-images.githubusercontent.com/47505178/165778512-fd34fbfd-cfc7-4752-b8a9-1633185b95b4.png)

**Comment by sonorah** [comment]
We've previously seen similar issues with scrollers on windows only, but I'm seeing this on my mac as well.

**Comment by mvarnum** [comment]
Bobi, Annie, and I were not able to recreate this on our MacBooks

**Comment by cbenayed** [comment]
I didn't have this bug on my mac.
