### ISSUE TITLE
prevent users from applying Next State filters if not applicable

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#654]
if a model does not have a rescue, task, or goal, prevent users from applying Next State whole model filters that have to do with to resources, tasks, or goals

**Comment by anishaj149** [comment]
Some times I get a pop up telling me I can't other times I do not. But It seems I am never able to select things that conflict relating to the intentions, so it works

**Comment by sonorah** [comment]
Works for me!

**Comment by anishaj149** [comment]
Looks good
