### ISSUE TITLE
prevent users from selecting conflicting filters in Next State

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#656]
for example, prevent a user from being able to select both most resource satisfied and least resource satisfied filters in Next State

**Comment by anishaj149** [comment]
If I click "Most Goal Satisfied" I can click "least Actor Involved" and then "Most Actor Involved." Its a conflicting state, and also there were no actors in my goal model.

**Comment by sonorah** [comment]
For me, when my model lacks an actor, "Least Actor Involved" and "Most Actor Involved" are not selectable (there's a pop-up warning me that I can't do that). However, after selecting "most goal satisfied", I can select pretty much everything else at once without warnings.

**Comment by anishaj149** [comment]
Looks good to me!
