### ISSUE TITLE
Adding Relative Assignments to "List of Assignments"

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#66]
This replaces the constraint view, removed in #65.
 
We are moving the constraint to the List of Assignments popup window, visible when the user clicks "View List of Assignments".

![screen shot 2017-09-17 at 7 35 53 pm](https://user-images.githubusercontent.com/6596937/30526006-99828ad0-9be0-11e7-8ff5-c5277ce343b3.png)

The screenshot above has a number of naming changes.

After the Absolute Intention Assignments, we will have a new table called "Relative Intention Assignments.
It will be a table with 4 columns: Epoch Boundary Name 1, Relationship, Epoch Boundary Name 2, and Add/Remove.

Relationship will have the value "=" and "<".

Epoch Boundary Name 1/2 will be a drop down with the elements listed in the Epoch Boundary Name column in the Absolute Intention Assignment table.

When the user clicks "Add" we should check that it is a valid relationship, same rules used in the current constraints view. If it is valid add a new row to the table and change the "Add" button to "Remove" for the accepted one, and save the constraint.

**Comment by g2hchang** [comment]
Do all three Absolute Relationship/Intention assignments and Relative Assignments need to appear at the same time in the dialog? Is it okay if I group Absolute Relative/Intention assignments together and allow users to toggle between Relative Assignments vs Absolute Assignments?

**Comment by amgrubb** [comment]
They all need to be in the same dialog.
You can implement scroll if it gets too big/long.
The user needs to be able to see everything at the same time.
