### ISSUE TITLE
The time point slider disappears when you select a color palette but you're in EVO "off" mode

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#663]
<img width="1160" alt="Screen Shot 2022-06-21 at 9 53 56 AM" src="https://user-images.githubusercontent.com/72589318/174816910-5875b88b-9fc4-4985-a973-073900534873.png">

**Comment by amgrubb** [comment]
@kkung9 and @Emkung Did this issue get fixed? The PR was closed? Please explain.

**Comment by kkung9** [comment]
@amgrubb I ended up fixing it a different (and better I think) way on a different branch in the process of trying to fix another issue, so I was going to push that branch when I finished fixing the other issue as well.
