### ISSUE TITLE
add warnings so users can't have no solutions in next state

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#666]
currently users can add as many filters as they want in next-state until there are no solutions, which causes EVO % mode to break (and a solution is still shown on the graph, which seems inaccurate) 
<img width="1485" alt="Screen Shot 2022-06-22 at 10 21 39 AM" src="https://user-images.githubusercontent.com/72589318/175054315-0e90fa2a-0cd9-433b-8aec-039093f40147.png">

**Comment by amgrubb** [comment]
PR was not merged into `develop`. Bug was not fixed.

**Comment by cbenayed** [comment]
EVO breaks because of the issue mentioned in #648  (next-state.js error line 148)
