### ISSUE TITLE
Page selection for Next State disappears with large numbers

### ISSUE THREAD

**Issue by YesugenB** [amgrubb/BloomingLeaf#667]
<img width="208" alt="Screen Shot 2022-06-22 at 11 42 46 AM" src="https://user-images.githubusercontent.com/59470488/175074301-ce86c16a-1be9-4d95-b80e-132445da64bd.png">

**Comment by mvarnum** [comment]
It looks like the page selection is still there, you just have to scroll over:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/55264239/216852892-0c3b8abb-28c6-4741-9dbf-93f4685f3e01.png">
