### ISSUE TITLE
If you set function to decreasing the default should be denied

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#668]
- [x] Default of decreasing value should be denied
- [x] Functions don't save the value if you change it (ex. if you set the end value to partially denied it resets to partially satisfied)
- [x] if you choose stochastic initial sat value should switch to (no value)

<img width="263" alt="Screen Shot 2022-06-22 at 3 52 31 PM" src="https://user-images.githubusercontent.com/72589318/175124244-eb6b3b52-cbdf-445c-9f70-81d88b78fec9.png">

**Comment by sonorah** [comment]
Joey and I fixed these. Check PR #673.
