### ISSUE TITLE
Allow "-" dash in intention name.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#67]
We restrict special characters in intention names.
Can we add "-" dashes back in as an allowed character?

We do allow "_", so I see no reason why we can't allow "-".
Was there a bug in passing the data to the backend for special characters?

I know having quotes in intention names is annoying, let's continue to restrict those.

**Comment by g2hchang** [comment]
I just want to make sure, the fix you want is when I specify node name that contains "-" character, it should not be treated as space, right?

<img width="463" alt="screen shot 2017-09-18 at 11 56 49 am" src="https://user-images.githubusercontent.com/16656280/30551474-82eb163e-9cd5-11e7-9995-c7818c818385.png">

**Comment by g2hchang** [comment]
Submitted a proposed fix.
Pull request #68
