### ISSUE TITLE
Increasing/decreasing font size is broken for some loaded models

### ISSUE THREAD

**Issue by i-m-foster** [amgrubb/BloomingLeaf#671]
When you load a model and increase/decrease font size sometimes only some words change size

<img width="625" alt="Screen Shot 2022-06-24 at 10 15 41 AM" src="https://user-images.githubusercontent.com/72589318/175973100-d2afda10-a395-47bc-973a-3349beb64727.png">

**Comment by violetbi** [comment]
Found a model in which only actors' name change size.

**Comment by Vbeany** [comment]
There are some models in V2 that when loaded into Bloomingleaf, when increasing and decreasing the size of the font will not be applied to all text in the goal model. The V3 models are working however. 

Models: 
Spadina opp before
Scheduler before
Purchasing before
WME before
