### ISSUE TITLE
Loading a Saved Model with Requests and Results breaks

### ISSUE THREAD

**Issue by YesugenB** [amgrubb/BloomingLeaf#674]
I tried to `Save Model, Analysis Requests, and Results' on this model with its results 
<img width="980" alt="Screen Shot 2022-07-20 at 9 33 32 AM" src="https://user-images.githubusercontent.com/59470488/179995956-f1f180b9-0432-409e-be03-a4291166a6c4.png">

After saving, I loaded the model but when I went to Analysis mode, the results weren't saved. 

Also, loading a model with results saved should also have more EVO options other than just `on/off`, as only simulating an additional result shows the `% Time State` EVO modes. 
<img width="980" alt="Screen Shot 2022-07-20 at 9 33 47 AM" src="https://user-images.githubusercontent.com/59470488/179996020-6cb58776-e607-42fd-92b7-f3b5e9e3d711.png">

**Comment by cbenayed** [comment]
unable to reproduce bug.
