### ISSUE TITLE
Satisfaction values not displaying correctly for some loaded models

### ISSUE THREAD

**Issue by violetbi** [amgrubb/BloomingLeaf#676]
In some loaded models in which the auto-layout algorithm was implemented (can tell from the name of the file "-output"), satisfaction values are displayed in digits instead of F, the bottom symbol which they are supposed to be. 
After clicking on load, the problem is resolved.
![issues-1](https://user-images.githubusercontent.com/88265939/183104166-60b9ffd2-ed9a-4412-aa21-4303473d7c50.png)
![issues-2](https://user-images.githubusercontent.com/88265939/183104175-98961b76-7a69-498a-bd65-65ba8fa4a535.png)
![issues-3](https://user-images.githubusercontent.com/88265939/183104192-b0769ae1-69d5-4e06-bc42-04c31a8e7217.png)
![issues-4](https://user-images.githubusercontent.com/88265939/183104202-bb4e836a-ad99-4807-b88d-a35f77476b37.png)

**Comment by cbenayed** [comment]
We will revisit this issue once the auto-layout algorithm is complete.
