### ISSUE TITLE
Visually distinguish solution source between Simulate Path and Next States

### ISSUE THREAD

**Issue by krhablutzel** [amgrubb/BloomingLeaf#685]
In the front end, we want to be able to tell whether a solution was generated from "Simulate Path" or chosen from the Next State viewer.

**Comment by amgrubb** [comment]
@cbenayed Can you investigate a possible solution that when the user clicks "Save and Close" in Next State, and the new path is created (e.g., "Result 2"), that "Result 2" is either underlined or has a star '*' before or after "Result 2" to indicate that it came from next state?

User clicks "Save and Close" in Next State window:
<img width="777" alt="Screenshot 2024-04-16 at 10 40 38 AM" src="https://github.com/amgrubb/BloomingLeaf/assets/6596937/f733948c-9429-4227-90b6-889173a0bffb">

"Result 2" appears under the Analysis pane on the right side:
<img width="531" alt="Screenshot 2024-04-16 at 10 40 52 AM" src="https://github.com/amgrubb/BloomingLeaf/assets/6596937/e3e2c598-dcb1-480c-b760-518b3f24cdb9">


Thanks you!
