### ISSUE TITLE
In Next State, display which # state is currently shown

### ISSUE THREAD

**Issue by krhablutzel** [amgrubb/BloomingLeaf#686]
In the Next State window, we want to display in the interface which number state is currently shown.

**Comment by amgrubb** [comment]
In this example, it is currently showing the 3rd state in the next state window.
`Time Point #3 of 8` should be displayed above "Number of States".
<img width="1273" alt="Screen Shot 2023-01-16 at 7 58 59 PM" src="https://user-images.githubusercontent.com/6596937/212787416-9d70dc72-977e-4736-80dd-46621330f320.png">
