### ISSUE TITLE
Font resize does not apply when adding new actors

### ISSUE THREAD

**Issue by mvarnum** [amgrubb/BloomingLeaf#689]
If you change the font size in your model, then add a new actor element, the actor will be displayed with the default font size:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/55264239/199737421-d996ee43-f911-420f-83a2-748c295970ba.png">

**Comment by Cyrine-BA** [comment]
It seems like you need to click on something else (a goal, soft goal, or resource) before the actor font size refreshes
