### ISSUE TITLE
Unable to make links reappear after meeting conflicting values

### ISSUE THREAD

**Issue by violetbi** [amgrubb/BloomingLeaf#697]
When intentions' sat values are in conflict, we'll set them to disappear. But currently, when the sat value isn't in conflict anymore, we cannot get the links back. Tried to solve it in a way to make every link appear when moving the slider but failed to work.
To recreate: select merge-1 model and add a few intentions and links
Click on analysis and simulate path
<img width="921" alt="image" src="https://user-images.githubusercontent.com/88265939/207672494-8135f819-a62b-4e67-bf4c-e757e9ac39de.png">
<img width="921" alt="image" src="https://user-images.githubusercontent.com/88265939/207673694-53735c96-ae91-44a7-97b7-ef447b4f406a.png">
<img width="921" alt="image" src="https://user-images.githubusercontent.com/88265939/207672576-efe526e9-c93f-481e-80a6-914ccf521b6a.png">

**Comment by cbenayed** [comment]
bug fixed
