### ISSUE TITLE
Absolute Values Table: Change table order.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#7]
In the absolute values table is as follows:
![screen shot 2017-08-14 at 2 33 09 pm](https://user-images.githubusercontent.com/6596937/29285757-949296e4-80fd-11e7-9559-5e01fd8c76af.png)

We want to switch the columns in the Nodes table.
Should be: 

> Epoch Boundary Name - Function - Assigned Time - Action

Where first entry would now be:

> Resource_1 : A - SD - None - Unassign

Note: We are merging the old Epoch Boundary and Node name, instead putting the node name first followed by " : " then the Epoch Boundary.

**Comment by Akira83** [comment]
Changed in marcel-dev branch.
