### ISSUE TITLE
NBD/NBN function incorrect in backend.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#701]
After the reference time point has passed, only one of the intentions should be selected for the full time period...not one at each time point as shown below.
<img width="471" alt="Screen Shot 2023-01-17 at 3 45 54 PM" src="https://user-images.githubusercontent.com/6596937/213008748-76afa069-5741-45c4-bcf6-0fb4dacef1ca.png">

**Comment by cbenayed** [comment]
bug fixed
