### ISSUE TITLE
Update front/backend to accommodate output of modeling merging operation

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#703]
When 'no' links are created, there are not able to be processed by the backend.

**Comment by amgrubb** [comment]
@anishaj149 
The model you send me `S8-out.json` has `"maxAbsTime": 1`. How is the merging of the `maxAbsTime` handled by Merge?
I would assume that the resulting `maxAbsTime` should be a larger number and that this should be handled by the part that merges the timeline.

**Comment by anishaj149** [comment]
In the two models that are merged to produce S8-out.json (S8-Part2.json and S8-Part4.json) it seems that maxAbsTime is 1, so I think S8-out.json is correct

**Comment by amgrubb** [comment]
Ok, great.

**Comment by cbenayed** [comment]
bug fixed in #702
