### ISSUE TITLE
Clear old analysis data when switching between Modeling and Analysis

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#71]
"currentState":"5|5","initialAssignedEpoch":"TA0_0,E0001_74,TA2_2,TA1_1,TA4_4,TE8_74,E0000_72,TA3_3,TE7_72,TA6_6,TA5_5"

**Comment by Akira83** [comment]
Working on local. Need testing on server.

**Comment by Akira83** [comment]
Was cleaning data in incorrect place. Corrected that, it cleans data when switch mode Analysis-> modeling

**Comment by Akira83** [comment]
Tested on Server and it erases the old analysis data when the user changes from analysis to modeling.
