### ISSUE TITLE
Need to be able to scroll on methodology popup

### ISSUE THREAD

**Issue by mollyd13** [amgrubb/BloomingLeaf#727]
Right now, if you want to be able to see the whole popup you need to scroll the whole page. We want to have a scroll bar in the popup so that you don't have to scroll the whole page anymore.

**Comment by cbenayed** [comment]
Are you guys using the showAlert() function for popups? If so, maybe consider switching to the popup_frame, popup_content, and popup_header that are already available in CSS. Then you can set it to scrollable there =)
