### ISSUE TITLE
Evolving Relationships Error with Dropdown and Link element.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#75]
See screenshot:
![screen shot 2017-09-21 at 9 06 15 pm](https://user-images.githubusercontent.com/6596937/30725252-42459846-9f11-11e7-9854-e94dc0745e8a.png)

Then link should look like this:
![screen shot 2017-09-21 at 9 11 10 pm](https://user-images.githubusercontent.com/6596937/30725273-7846064c-9f11-11e7-9c9f-412d25b20aa3.png)

It looks like it was created as a result of #51

**Comment by amgrubb** [comment]
The dropdown boxes seem to work for all the cases when the No Relationship is second, but don't work at all if the No Relationship is first.
![screen shot 2017-09-21 at 9 14 19 pm](https://user-images.githubusercontent.com/6596937/30725324-f640b8e4-9f11-11e7-9c5c-28f325566e36.png)

**Comment by g2hchang** [comment]
Hi Alicia,
I pushed the fix, seems to show correct value.
Please have a look at this branch : https://github.com/amgrubb/BloomingLeaf/tree/evolRelationshipDropdown

It appears that in line 207 of LinkInspector.js, old version had
 var end = $("#link-type-end").val("no"); . But apparently,  line 202 
 calls this function this.appendSelectValues($("#link-type-end"), "A"); and in line 307, it's already set to   select.val("no");. So I think there's some issue with overriding existing value and I am not sure about the exact cause. But apparently, setting it to  var end = $("#link-type-end").val(); , which just gets the current value of $("#link-type-end") seems to show the correct value.

<img width="1151" alt="screen shot 2017-09-21 at 11 05 30 pm" src="https://user-images.githubusercontent.com/16656280/30727891-16260dd4-9f22-11e7-8e27-341151da4b6b.png">

**Comment by Akira83** [comment]
Tested and it seems to being work fine.
