### ISSUE TITLE
Unclear how to enter Absolute Time Points

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#8]
![screen shot 2017-08-14 at 2 38 31 pm](https://user-images.githubusercontent.com/6596937/29285936-43c0b614-80fe-11e7-9970-2474d3850bad.png)

In the Analysis box it is unclear whether to enter the time points as 5, 8, 22 or 5 8 22.
Below the word "Analysis" add in a smaller font (e.g. 5, 8, 22) with the correct formate.

**Comment by Akira83** [comment]
Added the line (e.g. 5 8 22) under the "Absolute Time Points" box.
Changes in marcel-dev.

**Comment by amgrubb** [comment]
Sorry, can you put it above the box and below the text.
![screen shot 2017-08-16 at 12 16 36 pm](https://user-images.githubusercontent.com/6596937/29373951-c4a206b8-827d-11e7-99a6-ce166ea81ba1.png)
