### ISSUE TITLE
ElementInspector select sync BUG

### ISSUE THREAD

**Issue by Akira83** [amgrubb/BloomingLeaf#83]
In ElementInspector the select options need to be correlated.
Pull version before refactoring and verify the rules.

**Comment by Akira83** [comment]
Just compared the current version with the last Navie commit, there are some small changes for other bugs correction but definitely no refactoring was made, it is basically the same file. I didn't got the last Navie commit back because there are other commits above to solve different bugs. Probably in some of these corrections this problem appeared. I will investigate more.

**Comment by Akira83** [comment]
I will refactor this view and correct the BUG.

**Comment by Akira83** [comment]
How is represented the value Unknow in 4 bits?

**Comment by amgrubb** [comment]
That's a good question, let me think about it.

**Comment by amgrubb** [comment]
@Akira83 There is still a few errors. Let me know if you are able to reproduce them.
1. When you delete a link, the dynamics associated with the nodes connected to the link are deleted. 
2. The graph is still not updating correctly around the increase/decrease bug.

**Comment by Akira83** [comment]
The selection are now sync. I will close this issue and open the ones related to these two new bugs.
