### ISSUE TITLE
Send Relative and Absolute Assignments to backend

### ISSUE THREAD

**Issue by g2hchang** [amgrubb/BloomingLeaf#87]
Send the values that are saved in relative and absolute assignments to the backend.

**Comment by amgrubb** [comment]
I created a branch `feat-abs-toback` for this feature.
I started it with commit: 565a17c5ee45d8452ed535ef16fb4c9ff2ac7e64 

Here are the noted from the commit:
1. Absolute Intention Assignments.
2. Relative Intention Assignments.
3. Absolute Relationship Assignments.

1 & 2 should create an `InputConstraint.js` object.
1 has the type “A” and an absolute value.
2 has no absolute value but has a type “<“ or “=“
See TODO in file to add the absolute values.

3 should create a `InputLink.js` object.
See TODO in file. Need to get the absolute value as an integer.

I updated the appropriate java files to make pass the correct object.

Note: InputLink does not need the markedValue, it is never used by the
backend.

**Comment by amgrubb** [comment]
@g2hchang I am ready for you to start working on this. You can checkout my feature branch `feat-abs-toback` to continue development.

**Comment by amgrubb** [comment]
IMPORTANT: When you assign the absolute value for a decomposition link, you must set it for all decomposition links with the same destination node.

**Comment by amgrubb** [comment]
TODO: Refactor Model Constraint Code #72.
Although the blue button is removed, code refactoring still needs to be done (Related to #65).

**Comment by g2hchang** [comment]
Created a pull request #105
