### ISSUE TITLE
Behaviour when returning to Modeling view after a Simulation

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#9]
If you are in the simulation view and select Model -> From Current State the behaviour is incorrect unless you are in the initial state.
Option 1:
Change button to be "From Initial State" and update code.
Option 2:
Fix code and figure out all the semantics of what happens with all dynamic functions (including UD functions) when you return in an intermediate state.
Also figure out what happens when you are on a conflicting state and you return to the modeling view.

**Comment by Akira83** [comment]
Option 1 seems to be the best for now... Changes done in Marcel-dev.
I will think about option 2 later.

**Comment by amgrubb** [comment]
This is partially corrected. It still doesn't work for MP and other dynamics.

**Comment by Null7** [comment]
It worked fine for MP during testing, can we close this?

**Comment by amgrubb** [comment]
Yes
