### ISSUE TITLE
Cycle Detection Enhancement

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#94]
I am so happy that cycle detection works well. :)

How do I know if this is one cycle or 7? What about a cycle within a cycle. We should talk about how to distinguish between cycles or what happens if there is a cycle within a cycle.

Can we improve this visual?

[TYPlanningBoard (11).json.txt](https://github.com/amgrubb/BloomingLeaf/files/1384036/TYPlanningBoard.11.json.txt)

![screen shot 2017-10-13 at 5 20 04 pm](https://user-images.githubusercontent.com/6596937/31566948-ef682a36-b03a-11e7-845b-215ce6650bf0.png)

**Comment by amgrubb** [comment]
Here is another example. Why is `Goal_0` highlighted? Also, can each cycle be a different color?

<img width="901" alt="Screen Shot 2019-07-24 at 2 53 51 PM" src="https://user-images.githubusercontent.com/6596937/61820413-e6741880-ae22-11e9-8bad-1f6d130a54ff.png">

**Comment by oibrahim22** [comment]
The issue was fixed and the different color cycle has been implemented
