### ISSUE TITLE
Check if results are for current simulation.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#95]
We need to add a test when calling the backend to see if the current output file is even for the model requested.
When the backend fails, the front-end tried to show the results from a previous simulation request.

Maybe compare the number of intentions in the request file and the number of intentions in the result files...as a start?

**Comment by g2hchang** [comment]
Can this be part of #86  https://github.com/amgrubb/BloomingLeaf/issues/86 ? I found a suitable testing framework and I just need to write few initial test cases. And then, we can continuously add a test?

**Comment by Akira83** [comment]
I think there are two different ways to solve this problem:
1) Name the file with a different name every execution (could be something like the model title)
More difficult but better because this way if two people are executing the program at same time this type of error will not occur.
- Changes in the frontent-backend data to include the model name.
- Changes in the backend to create the correspondent file, also create a file management to erase old files. Otherwise the server will be fulfil with old models.

2) Create a error flag in the backend.
(Easy but doesn't solve the problem if there are 2 people executing the program at the same time)
- Change the backend to add a flag to the AJAX execution.
- Add a popup window in the frontend to show de error message and don't change the current model.

**Comment by amgrubb** [comment]
@g2hchang - This should be part of the test framework, but we need a run-time test as well.

**Comment by amgrubb** [comment]
For the short-term, let's choose #2.
I can make the updates to the backend then we can test it.

For the long-term, #1 is preferable.
We should get the unique id from the graph and use that to name the files. We would also need a script to delete all past analysis files at ~3am.

**Comment by amgrubb** [comment]
@Akira83 I finished the implementation. Can you please test the `flag-errors' branch.

**Comment by Akira83** [comment]
Corrected some bugs.
I tried to see if the message error is correct but all cases I tested or they where with a RuntimeException and not printed to output file.

Here is the link to test.
http://www.cs.utoronto.ca/~marcel/dev-blooming/

**Comment by amgrubb** [comment]
Using http://www.cs.utoronto.ca/~marcel/dev-blooming/
I don't get any pop up for the errors.

**Comment by Akira83** [comment]
Could you just send me a test case that has an error for sure. Because as I said, all that I tried throws back RuntimeExceptions. This kind of exceptions are not going to be shown to the user, only the ones that write some message on output.out file.

**Comment by amgrubb** [comment]
Sorry for the delay, I hope you have time to look at this soon.

We decided that the user would see RuntimeExceptions and the backend outputs them to the output.out file. If there is a RuntimeException in the writing to the output file we will not get this.

### For example.

Here is a model that results in an error (runtime).
![screen shot 2017-11-02 at 8 56 47 am](https://user-images.githubusercontent.com/6596937/32327215-1b136eea-bfac-11e7-8794-54876e61c3cc.png)

The output file on the server get this.
![screen shot 2017-11-02 at 8 57 07 am](https://user-images.githubusercontent.com/6596937/32327245-3d8221e2-bfac-11e7-871f-355b4330f270.png)

But it won't display the message, and here is the error.
![screen shot 2017-11-02 at 8 57 32 am](https://user-images.githubusercontent.com/6596937/32327261-46f86c40-bfac-11e7-9930-bb0b31ae6c80.png)

**Comment by Akira83** [comment]
Which branch are the modifications?
Because when I try to execute this example my output.out is different:

{
  "elementList": [],
  "allSolution": [],
  "finalAssignedEpoch": [],
  "finalValueTimePoints": [],
  "relativeTimePoints": 4
}

**Comment by Akira83** [comment]
I found the problem... I don't know how to solve yet.

Problem: when executing Blooming.jar in the server for some reason everything is being written in the console and not in the output.out, even with the DEBUG flag set as false. 
And in the output.out  nothing is being written.

When executing in Eclipse everything works fine...

**Comment by amgrubb** [comment]
That depend on where your `executeJava.cgi` is pointing.
`os.system("/u/amgrubb/java/jre1.8.0_66/bin/java -jar /u/amgrubb/bin/DevBlooming.jar")`

On my server I have both DevBlooming.jar and Blooming.jar, depending on which version I am using.

I am testing on: http://www.cs.utoronto.ca/~amgrubb/dev/blooming/

**Comment by Akira83** [comment]
Every time I test I build a new jar and upload to server...
First I execute it locally and then convert to jar and upload to server.
But the execution is not being the same way when locally and server...

I'm not execution by the executeJava.cgi... I run it manually to check if there is any error not being sent to ajax...

I'm investigating that... it seems to occur only for exceptions... I just tried to write a random output.out and it works... so... I will try to figure out...

**Comment by Akira83** [comment]
There are two problems:
1 - The java is not executing in time to fill the output.out before being sent back to frontend.
2 - The error message is not a valid json.
It was very hard to find this two problems... because they are different and happened on different times... I will correct then and test it

**Comment by Akira83** [comment]
Version with modifications.

The error message is working.
There is a small time gap between ajax calls.

http://www.cs.utoronto.ca/~marcel/dev-blooming/

**Comment by amgrubb** [comment]
@Akira83 Did you commit your final change with the small time gap?
I created a pull request, but don't see your final commit.
